name: CDK Deployment
run-name: ${{ github.actor }} is deploying Snake 🐍
on: [workflow_dispatch]
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node/NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: |
          npm install
          CI=false npm run build
      
      - name: Move to Infra directory
        run: cd infrastructure

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2.1.1
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: testsecret
          #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2.1.1
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'InfrastructureStack'
          cdk_args: '--require-approval never'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: testsecret
          #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
