name: CI Pipeline
run-name: ${{ github.actor }} is deploying Snake 🐍
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node/NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build
        run: |
          npm install
          CI=false npm run build

      - name: CDK diff
        uses: youyo/aws-cdk-github-actions@v2.1.4
        with:
          cdk_subcommand: 'diff'
          working_dir: './infrastructure'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: CDK deploy
        uses: youyo/aws-cdk-github-actions@v2.1.4
        with:
          cdk_subcommand: 'deploy'
          working_dir: './infrastructure'
          cdk_stack: 'InfrastructureStack'
          cdk_args: '--require-approval never'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
